### ISSUE TITLE
PhpStorm does not find trait method in short closure

### ISSUE THREAD

**Issue by christophrumpel** [JetBrains/pest-intellij#386]
I am trying to access a method from a trait inside this short closure in the fake method of the HTTP facade, and PhpStorm does not recognize this method from the trait.
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/1394539/200889499-c7a83c0b-ab8d-4873-adf4-73bf3dd7efa2.png">

Here is the trait:
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/1394539/200889533-4dac37b7-3c54-49db-ad0a-3e7065ab0c6d.png">

**Comment by isfedorov** [comment]
@christophrumpel since as of now Pest plugin is maintained by PhpStorm team, we are going to gradually move all the reports from GitHub to YouTrack. I've filled a dedicated ticket for this particular problem [WI-75120](https://youtrack.jetbrains.com/issue/WI-75120) so you can track the state and vote for this issue there. Thank you for the report! For now I'm going to close this ticket. If you have any comments or other problems with Pest plugin, please report them to [YouTrack](https://youtrack.jetbrains.com/newIssue?project=WI)
