### ISSUE TITLE
InvalidPathException due to Glob Patterns in PhpStorm

### ISSUE THREAD

**Issue by mozex** [JetBrains/pest-intellij#474]
**Describe the bug**
I have contributed a [Pull Request](https://github.com/pestphp/pest/pull/829) to Pest that introduces glob pattern support in the `->in()` method. While the PR has been successfully merged, it appears to introduce a compatibility issue with PhpStorm, where the IDE persistently encounters errors when trying to interpret these patterns.

The Pest IntelliJ plugin currently doesn't support glob patterns for PHP in Pest.php file. The glob pattern feature allows Pest to accept any string that glob can, not only *, but the Pest plugin fails to resolve this.

**To Reproduce**

Open `Pest.php` file in a project that utilizes Pest.
Add a uses function with glob pattern like: `->in('../Modules/*/Tests/Browser');`
Observe that Pest plugin fails to resolve the glob pattern.

**Expected behavior**
The Pest plugin should be able to handle and correctly interpret glob patterns as used in Pest, extending the functionality to allow matching with directory and file names.

**Desktop (please complete the following information):**
OS: Windows 11
IntelliJ Version: PhpStorm 2023.1.2
Plugin Version 1.10.1

**Additional context**
This issue might need significant code changes as Kotlin doesn't have a built-in glob function like PHP. Possible solution involves using Java's java.nio.file.Files and java.nio.file.Path classes to find files that match the glob pattern. This could have performance implications, so implementing some form of caching or limiting the depth of the directory traversal might be necessary.

Here's the error log I'm encountering:
```shell
com.intellij.diagnostic.PluginException: TypeProvider contract violation? by class com.pestphp.pest.types.ThisTypeProvider on test() [Plugin: com.pestphp.pest-intellij]
...
Caused by: java.nio.file.InvalidPathException: Illegal char <*> at index 17: tests/../Modules/*/Tests/Browser
...
```

**Comment by olivernybroe** [comment]
Hi, thanks for making awareness of this BC in Pest :) 

Yeah, there is multiple things in the plugin that will break because of this. Hmm, not sure if we can use those Java classes as I think they dependent on the file system the IDE is installed on which is not necessarily the case in PhpStorm. 
There is likely something identical in IntelliJ which could be used, else a custom solution would have be build

**Comment by mozex** [comment]
Hope this gets resolved soon, it is causing a lot of problems to the PhoStorm, or at least until it is resolved, it would be great to ignore these patterns to avoid errors.

**Comment by olivernybroe** [comment]
I won't personally have time for it right now, also because I don't use glob pattern feature myself. 

However PR's are welcome, even to just solve it for crashing.
Also looks like we are already using `java.nio.file.Path`, so a solution using that would be acceptable.

**Comment by mozex** [comment]
Ok, I'll try to work on it next week.

**Comment by isfedorov** [comment]
@mozex pest plugin is being maintained by PhpStorm team now and we are going to gradually move all the tickets from GitHub to [YouTrack](https://youtrack.jetbrains.com/issues/WI) so that we have only one source of tickets. I've filled [WI-75194](https://youtrack.jetbrains.com/issue/WI-75194/Add-support-for-glob-patterns-in-Pest-config) for this issue and going to close this ticket. Please vote for the ticket at YouTrack to receive updates on it. If you have any other issues, please report them to YouTrack
