### ISSUE TITLE
Single word test reporting an error

### ISSUE THREAD

**Issue by nunomaduro** [JetBrains/pest-intellij#523]
<img width="268" alt="Screenshot 2024-03-08 at 22 51 52" src="https://github.com/JetBrains/pest-intellij/assets/5457236/54e0a290-99f3-4026-b64b-321500ca5f91">

**Comment by olivernybroe** [comment]
PhpStorm team collects all new issues in YouTrack, so if you could report it there instead, that would be great :) 
https://youtrack.jetbrains.com/newIssue?project=WI

**Comment by olivernybroe** [comment]
I have posted it for you 
https://youtrack.jetbrains.com/issue/WI-76533/Pest-Single-word-test-reporting-a-casing-error

**Comment by olivernybroe** [comment]
@pestretsov this was the last github issue that were open. I think you should utilize this to disable issues on the github repo and add youtrack to readme or something like that.

**Comment by smirok** [comment]
@nunomaduro It was fixed in [WI-75260](https://youtrack.jetbrains.com/issue/WI-75260) ([commit](https://github.com/JetBrains/pest-intellij/commit/c55a660465f687066b5b0658bd1c495dab803263) is here). These and the following changes will be available in PhpStorm 2024.1 and they are available now in PhpStorm 2024.1 EAP
